# Generated by Django 3.2.3 on 2021-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='description',
            field=models.TextField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
