# Generated by Django 3.2.3 on 2021-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_auto_20210717_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='image',
            field=models.ImageField(default=5, upload_to=None),
        ),
    ]
