# Generated by Django 3.2.3 on 2021-07-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_alter_doctormodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
