# Generated by Django 3.2.3 on 2021-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_auto_20210719_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacymodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pharmacymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
